---
- name: setup directories
  file: path={{ home }}/{{ item }} state=directory
  with_items:
    - scripts
    - tmp

- name: homebrew install
  homebrew:
    name={{ item }}
    state=present
    update_homebrew=yes
    upgrade_all=yes
  with_items:
    - ack
    - adns
    - asciinema
    - asciinema2gif
    - aspcud
    - aspell
    - autoconf
    - automake
    - bash
    - bash-completion@2
    - bmon
    - camlp4
    - capnp
    - cask
    - clasp
    - clingo
    - cmake
    - colordiff
    - confuse
    - coreutils
    - cscope
    - ctags
    - dark-mode
    - dash
    - ddate
    - diff-so-fancy
    - docker
    - docker-compose
    - docker-machine
    - emacs
    - enchant
    - erlang
    - exa
    - exiftool
    - exiv2
    - faac
    - ffmpeg
    - findutils
    - flac
    - fontconfig
    - freetype
    - gcore
    - gd
    - gdb
    - gdbm
    - gettext
    - gflags
    - gifsicle
    - git
    - git-lfs
    - glib
    - gmp
    - gnupg
    - gnuplot
    - gnutls
    - go
    - godep
    - graphviz
    - gringo
    - htop
    - htop-osx
    - hub
    - icu4c
    - ifstat
    - iftop
    - imagemagick
    - jemalloc
    - jpeg
    - jq
    - kafka
    - lame
    - libassuan
    - libevent
    - libffi
    - libgcrypt
    - libgpg-error
    - libidn2
    - libksba
    - libogg
    - libpng
    - librdkafka
    - libtasn1
    - libtiff
    - libtool
    - libunistring
    - libusb
    - libvorbis
    - libxml2
    - libyaml
    - lua
    - lz4
    - lzlib
    - macvim
    - mad
    - md5sha1sum
    - moreutils
    - netcat
    - nettle
    - nginx
    - ninja
    - node
    - npth
    - nsq
    - ocaml
    - ocamlbuild
    - onigurama
    - opam
    - openssl
    - p11-kit
    - pcre
    - phantomjs
    - pinentry
    - pkg-config
    - postgresql
    - pyenv
    - pypy
    - pypy3
    - python
    - python3
    - qcachegrind
    - qt
    - rabbitmq
    - rakudo-star
    - readline
    - redis
    - rocksdb
    - ruby
    - scons
    - selenium-server-standalone
    - serf
    - sl
    - sloccount
    - smlnj
    - snappy
    - sox
    - sqlite
    - stow
    - telnet
    - the_silver_searcher
    - tidy-html5
    - tig
    - tmux
    - tokyo-cabinet
    - tree
    - tsung
    - unixodbc
    - unrar
    - utf8proc
    - uwsgi
    - varnish
    - watch
    - webp
    - wget
    - wxmac
    - x264
    - xvid
    - xz
    - yajl
    - yasm
    - zeromq
    - zookeeper
    - neovim/neovim/neovim
    - vim
    # Languages
    - markdown
    - curl
    - iperf
    - nmap
    - tmux
    - zsh
    - awscli
    - gpg

- name: homebrew cask install
  homebrew_cask:
    name={{ item }}
    state=present
  with_items:
    - 0xed
    - 1password
    - 1password-cli
    - ableton-live-suite
    - auganizer
    - aurora
    - cardhop
    - cyberduck
    - daisydisk
    - dropbox
    - fantastical
    - firefox
    - github-desktop
    - google-cloud-sdk
    - google-chrome
    - google-drive
    - grammarly
    - hex-fiend
    - insomnia
    - iterm2
    - java
    - keybase
    - mactex
    - macvim
    - minecraft
    - native-access
    - nestopia
    - nordvpn
    - otx
    - pacifist
    - silverlight
    - skype
    - slack
    - spotify
    - steam
    - textual
    - the-unarchiver
    - torbrowser
    - transmission
    - vagrant
    - virtualbox
    - vlc
    - wireshark
    - xquartz
    - zoom

- name: os x specific configurations
  osx_defaults: domain={{ item.domain }} key={{ item.key }} type={{ item.type }} value={{ item.value }}
  with_items:
    # Default is 35 ms
    - { key: 'InitialKeyRepeat',                   domain: 'NSGlobalDomain',        type: 'int',   value: '15' }
    # Default is 0 ms
    - { key: 'KeyRepeat',                          domain: 'NSGlobalDomain',        type: 'int',   value: '2' }
    - { key: 'AppleKeyboardUIMode',                domain: 'NSGlobalDomain',        type: 'int',   value: '3' }
    # Allow key repeat, remove character accents
    - { key: 'ApplePressAndHoldEnabled',           domain: 'NSGlobalDomain',        type: 'bool',  value: 'false' }
    # Only show active apps in Dock
    - { key: 'static-only',                        domain: 'com.apple.dock',        type: 'bool',  value: 'true' }
    # Autohide Dock
    - { key: 'autohide',                           domain: 'com.apple.dock',        type: 'bool',  value: 'true' }
    # Don't show the Dashboard as a space
    - { key: 'dashboard-in-overlay',               domain: 'com.apple.dock',        type: 'bool',  value: 'true' }
    # Don't automatically rearrange spaces base on MRU
    - { key: 'mru-spaces',                         domain: 'com.apple.dock',        type: 'bool',  value: 'false' }
    # Show all filename extensions in Finder
    - { key: 'AppleShowAllExtensions',             domain: 'NSGlobalDomain',        type: 'bool',  value: 'true' }
    # Remove the warning when changing a file extension
    - { key: 'FXEnableExtensionChangeWarning',     domain: 'com.apple.finder',      type: 'bool',  value: 'false' }
    # Show the path bar in Finder
    - { key: 'ShowPathbar',                        domain: 'com.apple.finder',      type: 'bool',  value: 'true' }
    # Ask for password immediately after sleep
    - { key: 'askForPasswordDelay',                domain: 'com.apple.screensaver', type: 'float', value: '0' }
    # Expand the save dialog
    - { key: 'NSNavPanelExpandedStateForSaveMode', domain: 'NSGlobalDomain',        type: 'bool',  value: 'true' }
    # Enable tap to click for Trackpad
    - { key: 'com.apple.mouse.tapBehavior',        domain: 'NSGlobalDomain',        type: 'int',   value: '1' }
